In [7]:
import numpy as np

In [8]:
import torch

In [12]:
 t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [15]:
print('Rank of t :', t.ndim)
print('Shape of t :' , t.shape)

Rank of t : 1
Shape of t : (7,)


In [22]:
print('t[0] t[1] t[-1]=',t[0],t[1], t[-1] )
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

t[0] t[1] t[-1]= 0.0 1.0 6.0
[2. 3. 4.] [4. 5.]
[0. 1.] [3. 4. 5. 6.]


In [24]:
t = np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.],[10.,11.,12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [27]:
print(t.ndim)
print(t.shape)

2
(4, 3)


In [29]:
t = torch.FloatTensor([0.,1.,2.,3.,4.,5.,6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [32]:
print(t.dim())
print(t.shape)
print(t.size())
print(t[0],t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [33]:
t = torch.FloatTensor([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.],[10.,11.,12.]])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [34]:
print(t.dim())
print(t.size())
print(t[:,1])
print(t[:,1].size())
print(t[:,:-1])

2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


## Broadcasting

In [36]:
# Same shape
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])
print(m1 + m2)

tensor([[5., 5.]])


In [37]:
# Vector + scalar
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3]]) #3 -> [[3,3]] 으로 자동으로 바꿈
print(m1 + m2)

tensor([[4., 5.]])


In [38]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3],[4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


## Multiplication vs Matrix Multiplication

In [108]:
print()
print('--------------')
print('Mul vs Matmul')
print('--------------')
m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[1],[2]])
print(m1.matmul(m2))
m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[1],[2]])
print(m1 * m2)
print(m1.mul(m2))


--------------
Mul vs Matmul
--------------
tensor([[ 5.],
        [11.]])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


# Mean

In [43]:
t = torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [46]:
# Can't use mean() on integers
t = torch.LongTensor([1,2])
try:
    print(t.mean())
except Exception as exc:
    print(exc)

Can only calculate the mean of floating types. Got Long instead.


In [48]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [51]:
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


In [52]:
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


# Max and Argmax

In [59]:
t = torch.FloatTensor([[1,2],[4,3]])
print(t)

tensor([[1., 2.],
        [4., 3.]])


In [60]:
print(t.max())

tensor(4.)


In [61]:
print(t.max(dim=0)[0])
print(t.max(dim=0)[1])

tensor([4., 3.])
tensor([1, 1])


In [62]:
t.max(dim=1)

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 0]))

In [64]:
t = np.array([[[0,1,2],[3,4,5]],[[6,7,8],[9,10,11]]])
ft = torch.FloatTensor(t)
print(ft.shape)
print(ft)

torch.Size([2, 2, 3])
tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])


In [65]:
print(ft.view([-1,3]))
print(ft.view([-1,3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [66]:
print(ft.view([-1,1,3]))
print(ft.view([-1,1,3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


 # Squeeze

In [67]:
ft = torch.FloatTensor([[0],[1],[2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [68]:
ft.squeeze()

tensor([0., 1., 2.])

In [69]:
ft.squeeze().shape

torch.Size([3])

In [70]:
# dim을 지정하면 그 차원에 대해서만 squeeze를 수행함
ft.squeeze(dim=0)

tensor([[0.],
        [1.],
        [2.]])

 # Unsqueeze

In [72]:
ft=torch.Tensor([0,1,2])
print(ft.shape)

torch.Size([3])


In [75]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [76]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [77]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [83]:
ft = ft.unsqueeze(-1)
print(ft)
ft.shape
# dim = -1을 활용하면 계속 차원을 늘릴수가 있음

tensor([[[[[[[0.]]]]]],





        [[[[[[1.]]]]]],





        [[[[[[2.]]]]]]])


torch.Size([3, 1, 1, 1, 1, 1, 1])

# Type Casting

In [84]:
lt = torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [85]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [86]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [87]:
bt.long()

tensor([1, 0, 0, 1])

In [88]:
bt.float()

tensor([1., 0., 0., 1.])

 # Concatenate

In [89]:
x = torch.FloatTensor([[1,2],[3,4]])
y = torch.FloatTensor([[5,6],[7,8]])

In [91]:
print(torch.cat([x,y],dim=0))
print(torch.cat([x,y],dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


# Stacking

In [97]:
x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

torch.Size([2])


In [95]:
print(torch.stack([x,y,z]))
print(torch.stack([x,y,z],dim=1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [98]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0) ,z.unsqueeze(0) ], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


# Ones and Zeros

In [100]:
x = torch.FloatTensor([[0,1,2],[2,1,0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [103]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


# In-place Operation

In [104]:
x = torch.FloatTensor([[1,2],[3,4]])

In [109]:
print(x.mul(2.))
print(x)
print(x.mul_(2.))
print(x)
# 언더바를 사용하면 바로 그 메모리에 연산값 저장해버린다.

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
