# Lab 1: Tensor Manipulation

First Author: Seungjae Ryan Lee (seungjaeryanlee at gmail dot com)
Second Author: Ki Hyun Kim (nlp.with.deep.learning at gmail dot com)

<div class="alert alert-warning">
    NOTE: This corresponds to <a href="https://www.youtube.com/watch?v=ZYX0FaqUeN4&t=23s&list=PLlMkM4tgfjnLSOjrEJN31gZATbcj_MpUm&index=25">Lab 8 of Deep Learning Zero to All Season 1 for TensorFlow</a>.
</div>

## Imports

Run `pip install -r requirements.txt` in terminal to install all required Python packages.

In [1]:
import numpy as np
import torch

## NumPy Review

We hope that you are familiar with `numpy` and basic linear algebra.

### 1D Array with NumPy

In [32]:
t = np.array([[0., 1.], [2., 3.], [4., 5.], [6., 7.]])

print(t)

[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]]


In [34]:
print('Rank  of t: ', t.ndim) # ndim 차원 2차원.
print('Shape of t: ', t.shape) # shape 4 * 2.


Rank  of t:  2
Shape of t:  (4, 2)


In [25]:
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1]) # Element
print('t[2:3] t[2:-1]  = ', t[2:3], t[2:-1])   # Slicing
print('t[:2] t[3:]     = ', t[:2], t[3:])      # Slicing

t[0] t[1] t[-1] =  [1. 2. 3.] [4. 5. 6.] [10. 11. 12.]
t[2:3] t[2:-1]  =  [[7. 8. 9.]] [[7. 8. 9.]]
t[:2] t[3:]     =  [[1. 2. 3.]
 [4. 5. 6.]] [[10. 11. 12.]]


### 2D Array with NumPy

In [24]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [26]:
print('Rank  of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank  of t:  2
Shape of t:  (4, 3)


## PyTorch is like NumPy (but better)

### 1D Array with PyTorch

In [35]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [36]:
print(t.dim())  # rank
print(t.shape)  # shape
print(t.size()) # shape
print(t[0], t[1], t[-1])  # Element
print(t[2:5], t[4:-1])    # Slicing
print(t[:2], t[3:])       # Slicing

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


### 2D Array with PyTorch

In [37]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [38]:
print(t.dim())  # rank
print(t.size()) # shape
print(t[:, 1])
print(t[:, 1].size()) # 기준을 [] 로 생각.
print(t[:, :-1]) # :x 의 경우 x의 앞에 까지만 고려함. 따라서 [] 기준 으로 출력 되지만, 맨 뒤에 것을 제외하고 출력됨.

2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


### Shape, Rank, Axis

In [39]:
t = torch.FloatTensor([[[[1, 2, 3, 4],
                         [5, 6, 7, 8],
                         [9, 10, 11, 12]],
                       [[13, 14, 15, 16],
                        [17, 18, 19, 20],
                        [21, 22, 23, 24]]
                       ]]) # 판단은 [] 기준.

In [40]:
print(t.dim())  # rank  = 4
print(t.size()) # shape = (1, 2, 3, 4)

4
torch.Size([1, 2, 3, 4])


## Frequently Used Operations in PyTorch

### Mul vs. Matmul

In [41]:
print()
print('-------------')
print('Mul vs Matmul')
print('-------------')
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1 # 내적이 결과로 나옴 <= matmul.

m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2
print(m1.mul(m2)) # 대응 되는 값 끼리 연산 곱을 수행 <= mul


-------------
Mul vs Matmul
-------------
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


### Broadcasting

<div class="alert alert-warning">
    Carelessly using broadcasting can lead to code hard to debug.
</div>

In [42]:
# Same shape
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


In [43]:
# Vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # 3 -> [[3, 3]]
print(m1 + m2)

tensor([[4., 5.]])


In [44]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


### Mean

In [45]:
t = torch.FloatTensor([1, 2]) #자료형 과 같이 tensor 이 붙는 것을 확인
print(t.mean())

tensor(1.5000)


In [47]:
# Can't use mean() on integers
t = torch.LongTensor([1, 2])
try:
    print(t.mean())
except Exception as exc:
    print(exc) # torch.FloatTensor 만 기능이 구현되어있음

Can only calculate the mean of floating types. Got Long instead.


You can also use `t.mean` for higher rank tensors to get mean of all elements, or mean by particular dimension.

In [48]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [51]:
print(t.mean())
print(t.mean(dim=0)) # 같은 열
print(t.mean(dim=1)) # 같은 행
print(t.mean(dim=-1)) #최소 단위의 [] => max dim

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


### Sum

In [52]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [53]:
print(t.sum())
print(t.sum(dim=0)) # 같은 열
print(t.sum(dim=1)) # 같은 행
print(t.sum(dim=-1)) # 최소 단위의 []

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


### Max and Argmax

In [54]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


The `max` operator returns one value if it is called without an argument.

In [55]:
print(t.max()) # Returns one value: max

tensor(4.)


The `max` operator returns 2 values when called with dimension specified. The first value is the maximum value, and the second value is the argmax: the index of the element with maximum value.

In [58]:
print(t.max(dim=0)) # Returns two values: max and argmax
print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1])

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [61]:
print(t.max(dim=1))
print("\n")
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


### View

<div class="alert alert-warning">
    This is a function hard to master, but is very useful!
</div>

In [62]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],

              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [63]:
print(ft.view([-1, 3]))
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [64]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


### Squeeze

In [65]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [66]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


### Unsqueeze

In [67]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


In [68]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape) # 0 을 넣으면, 앞에 1, 이 생김.

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [69]:
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [76]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape) # 1 을 넣으면 뒤에 ,1 이 생김.

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [71]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


### Scatter (for one-hot encoding)

<div class="alert alert-warning">
    Scatter is a very flexible function. We only discuss how to use it to get a one-hot encoding of indices.
</div>

In [77]:
lt = torch.LongTensor([[0], [1], [2], [0]])
print(lt)

tensor([[0],
        [1],
        [2],
        [0]])


In [78]:
one_hot = torch.zeros(4, 3) # batch_size = 4, classes = 3
one_hot.scatter_(1, lt, 1)
print(one_hot) # 희소행렬 생성

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]])


### Casting

In [79]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt) # 아까 계산 함수 쓸 때가 안 된거지, 자체는 정의가 된다

tensor([1, 2, 3, 4])


In [80]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [81]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [82]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


### Concatenation

In [83]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [84]:
print(torch.cat([x, y], dim=0)) # 행이 추가됨
print(torch.cat([x, y], dim=1)) # 열이 추가됨

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


### Stacking

In [85]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [86]:
print(torch.stack([x, y, z])) # 행이 추가됨
print(torch.stack([x, y, z], dim=1)) # 열이 추가됨

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [88]:
print(torch.cat([x.unsqueez, y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([1., 4., 2., 5., 3., 6.])


### Ones and Zeros Like

In [ ]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

In [ ]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

### In-place Operation

In [ ]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [ ]:
print(x.mul(2.))
print(x)
print(x.mul_(2.))
print(x)

## Miscellaneous

### Zip

In [ ]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

In [ ]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)