# Lab1: Tensor Mainpulation

## Imorts

In [1]:
import numpy as np
import torch

## Numpy Review

### 1D Array with Numpy

In [2]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [3]:
print("Rank of t: ", t.ndim)
print("Shape of t: ", t.shape)

Rank of t:  1
Shape of t:  (7,)


In [6]:
print("t[0] t[1] t[-1] = ", t[0], t[1], t[-1])
print("t[2:5] t[4:-1] = ", t[2:5], t[4:-1])
print("t[:2] t[3:] = ", t[:2], t[3:])

t[0] t[1] t[-1] =  0.0 1.0 6.0
t[2:5] t[4:-1] =  [2. 3. 4.] [4. 5.]
t[:2] t[3:] =  [0. 1.] [3. 4. 5. 6.]


### 2D Array with Numpy

In [7]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [8]:
print("Rank of t: ", t.ndim)
print("Shape of t: ", t.shape)

Rank of t:  2
Shape of t:  (4, 3)


## Pytorch is like Numpy (but better)

### 1D array with pytorch

In [9]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [10]:
print(t.dim())
print(t.shape)
print(t.size())
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:]) 

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


### 2D array with pytorch

In [11]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [12]:
print(t.dim()) 
print(t.size())
print(t[:, 1])
print(t[:, 1].size())
print(t[:, :-1])

2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


### Shape, Rank, Axis

In [13]:
t = torch.FloatTensor([[[[1, 2, 3, 4],
                         [5, 6, 7, 8],
                         [9, 10, 11, 12]],
                       
                        [[13, 14, 15, 16],
                         [17, 18, 19, 20],
                         [21, 22, 23, 24]]
                       ]])

In [14]:
print(t.dim())
print(t.size())

4
torch.Size([1, 2, 3, 4])


## Frequently Used Operation in Pytorch

### Mul vs. Matmul

In [22]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape)
print('Shape of Matrix 2: ', m2.shape)
print(m1.matmul(m2)) # 행렬곱

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [23]:
print(m1 * m2) # broadcasting
print(m1.mul(m2))

tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


### Broadcasting

In [25]:
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2) # 5 5

tensor([[5., 5.]])


In [28]:
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # 3 -> [[3, 3]]
print(m1 + m2) # 4 5

tensor([[4., 5.]])


In [29]:
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
# 1 2    3 3
# 1 2    4 4
# 4 5
# 5 6
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


### Mean

In [30]:
t = torch.FloatTensor([1, 2])
print(t.mean()) # 1.5

tensor(1.5000)


In [31]:
# Can't use mean() on integers
t = torch.LongTensor([1, 2])
try:
    print(t.mean())
except Exception as exc:
    print(exc)

Can only calculate the mean of floating types. Got Long instead.


In [32]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [33]:
print(t.mean())       # 10/4 = 2.5
print(t.mean(dim=0))  # 2 3
print(t.mean(dim=1))  # 1.5 3.5
print(t.mean(dim=-1)) # 1.5 3.5

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


### Sum

In [34]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [35]:
print(t.sum())       # 10
print(t.sum(dim=0))  # 4 6
print(t.sum(dim=1))  # 3 7
print(t.sum(dim=-1)) # 3 7

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


### Max and Argmax

In [36]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [37]:
print(t.max()) # 4

tensor(4.)


In [38]:
print(t.max(dim=0)) # (max, argmax) return
print('Max: ', t.max(dim=0)[0]) # 3 4
print('Argmax: ', t.max(dim=0)[1]) # 1 1

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [39]:
print(t.max(dim=1))  # 2 4 / 1 1 
print(t.max(dim=-1)) # 2 4 / 1 1

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


### View

In [41]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],

              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft.shape) # 2 2 3

torch.Size([2, 2, 3])


In [42]:
print(ft.view([-1, 3]))
print(ft.view([-1, 3]).shape) # 4 3

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [43]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape) # 4 1 3

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


### Squeeze

In [44]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape) # 3 1

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [45]:
print(ft.squeeze())
print(ft.squeeze().shape) # 3

tensor([0., 1., 2.])
torch.Size([3])


### Unsqueeze

In [46]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape) # 3

torch.Size([3])


In [47]:
print(ft.unsqueeze(0)) #dim=0에 1을 넣어
print(ft.unsqueeze(0).shape) # 1 3

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [48]:
print(ft.view(1, -1))
print(ft.view(1, -1).shape) # 1 3

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [50]:
print(ft.unsqueeze(1)) #dim=1에 1을 넣어
print(ft.unsqueeze(1).shape) # 3 1

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [51]:
print(ft.unsqueeze(-1)) #dim=-1에 1을 넣어
print(ft.unsqueeze(-1).shape) # 3 1

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


### Scatter (for one-hot encoding)

In [52]:
lt = torch.LongTensor([[0], [1], [2], [0]])
print(lt)

tensor([[0],
        [1],
        [2],
        [0]])


In [64]:
one_hot = torch.zeros(4, 3) # batch_size = 4, classes = 3
one_hot.scatter_(1, lt, 1)
print(one_hot)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]])


### Casting

In [66]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


In [67]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [68]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [69]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


### Concatenation

In [70]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [71]:
print(torch.cat([x, y], dim=0))
print(torch.cat([x, y], dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


### Stacking

In [72]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [73]:
print(torch.stack([x, y, z]))
print(torch.stack([x, y, z], dim=1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [74]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


### Ones and Zeros Like

In [75]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [76]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


### In-place Operation

In [77]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [78]:
print(x.mul(2.))
print(x)
print(x.mul_(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


## Miscellaneous

### Zip

In [79]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [80]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9
