In [1]:
import numpy as np
import torch

## 1D Array with numpy

In [2]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [3]:
print("Rank of t: ", t.ndim)
print("Shape of t: ", t.shape)

Rank of t:  1
Shape of t:  (7,)


In [4]:
print("t[0] t[1] t[-1] = ", t[0], t[1], t[-1])
print("t[2:5] t[4:-1] = ", t[2:5], t[4:-1])
print("t[:2] t[3:] = ", t[:2], t[3:])

t[0] t[1] t[-1] =  0.0 1.0 6.0
t[2:5] t[4:-1] =  [2. 3. 4.] [4. 5.]
t[:2] t[3:] =  [0. 1.] [3. 4. 5. 6.]


## 2D Array with numpy

In [5]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [6]:
print("Rank of t: ", t.ndim)
print("Shape of t: ", t.shape)

Rank of t:  2
Shape of t:  (4, 3)


## 1D Array with PyTorch

In [7]:
six_array = [0., 1., 2., 3., 4., 5., 6.]
nd_array = [[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]]
t = torch.FloatTensor(six_array)
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [9]:
print(t.dim())
print(t.shape)
print(t.size())
print("t[0] t[1] t[-1] = ", t[0], t[1], t[-1])
print("t[2:5] t[4:-1] = ", t[2:5], t[4:-1])
print("t[:2] t[3:] = ", t[:2], t[3:])

1
torch.Size([7])
torch.Size([7])
t[0] t[1] t[-1] =  tensor(0.) tensor(1.) tensor(6.)
t[2:5] t[4:-1] =  tensor([2., 3., 4.]) tensor([4., 5.])
t[:2] t[3:] =  tensor([0., 1.]) tensor([3., 4., 5., 6.])


## 2D Array with PyTorch

In [10]:
t = torch.FloatTensor(nd_array)
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [11]:
print(t.dim())
print(t.size())
print(t[:, 1])
print(t[:, 1].size())
print(t[:, :-1])

2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


## Broadcasting

In [12]:
# same shape
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


In [14]:
# vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3]])
print(m1 + m2)

tensor([[4., 5.]])


In [13]:
# 2 x 1 vector + 1 x 2 vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


In [15]:
print()
print("-----------------")
print("Mul vs Matmul")
print("-----------------")
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print("Shape of matrix 1: ", m1.shape) # 2 x 2
print("Shape of matrix 2: ", m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1

m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print("Shape of matrix 1: ", m1.shape) # 2 x 2
print("Shape of matrix 2: ", m2.shape) # 2 x 1
print(m1 * m2) # 2 x 1
print(m1.mul(m2))


-----------------
Mul vs Matmul
-----------------
Shape of matrix 1:  torch.Size([2, 2])
Shape of matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
Shape of matrix 1:  torch.Size([2, 2])
Shape of matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


## Mean

In [16]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [17]:
# Can't use mean() on integers
t = torch.LongTensor([1, 2])
try:
    print(t.mean())
except Exception as exc:
    print(exc)

Can only calculate the mean of floating types. Got Long instead.


you can also user **t.mean** for higher rank tensors to get mean of all elements, or mean by particular dimension

In [18]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [19]:
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


## Sum

In [20]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [21]:
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


In [22]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


The **max** operator returns one value if it is called without an argument

In [23]:
print(t.max()) # returns one value: max

tensor(4.)


The **max** operator returns 2 values when called with dimension specified. The first value is the  
maximum value, and the second value is the argmax: index of the element with maximum value.

In [24]:
print(t.max(dim=0)) # returns 2 values: max and argmax
print("Max: ", t.max(dim=0)[0])
print("Argmax: ", t.max(dim=0)[1])

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [25]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


## View (Reshape)

In [26]:
t = np.array([
    [[0, 1, 2],
    [3, 4, 5]],
    
    [[6,7,8],
     [9,10,11]]
])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [27]:
print(ft.view([-1,3]))
print(ft.view([-1,3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [28]:
print(ft.view([-1,1,3]))
print(ft.view([-1,1,3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


## Squeeze

In [29]:
ft = torch.FloatTensor([[0],[1],[2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [30]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


## Unsqueeze

In [31]:
ft = torch.Tensor([0,1,2])
print(ft.shape)

torch.Size([3])


In [32]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [33]:
print(ft.view(1,-1))
print(ft.view(1,-1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [34]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [35]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


## Type Casting

In [36]:
lt = torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [37]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [39]:
bt = torch.ByteTensor([True,False,False,True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [40]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


## Concatenate

In [41]:
x = torch.FloatTensor([[1,2], [3,4]])
y = torch.FloatTensor([[5,6], [7,8]])

In [42]:
print(torch.cat([x,y], dim=0))
print(torch.cat([x,y], dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


## Stacking

In [43]:
x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

In [44]:
print(torch.stack([x,y,z]))
print(torch.stack([x,y,z], dim=1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [45]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


## Ones and Zeros

In [46]:
x = torch.FloatTensor([[0,1,2],[2,1,0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [48]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


## In place Operation

In [49]:
x = torch.FloatTensor([[1,2],[3,4]])

In [50]:
print(x.mul(2.))
print(x)
print(x.mul_(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
