# Tensor Manipulation
### CUAI 4기 임상준

In [16]:
import numpy as np
import torch

## 1D Array with Numpy

In [5]:
t = np.array([0.,1.,2.,3.,4.,5.,6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [6]:
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank of t:  1
Shape of t:  (7,)


In [7]:
print('t[0]   t[1]    t[-1] = ', t[0], t[1], t[-1])  #Element
print('t[2:5] t[4:-1]       = ', t[2:5], t[4:-1])    #Slicing
print('t[:2]  t[3:]         = ', t[:2], t[3:])       #Slicing

t[0]   t[1]    t[-1] =  0.0 1.0 6.0
t[2:5] t[4:-1]       =  [2. 3. 4.] [4. 5.]
t[:2]  t[3:]         =  [0. 1.] [3. 4. 5. 6.]


## 2D Array with Numpy

In [8]:
t = np.array([[1.,2.,3.], [4.,5.,6.], [7.,8.,9.], [10.,11.,12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [9]:
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank of t:  2
Shape of t:  (4, 3)


## 1D Array with Pytorch

In [17]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

AttributeError: module 'torch' has no attribute 'FloatTensor'

In [18]:
print(t.dim())            # rank
print(t.shape)            # shape
print(t.size())           # shape
print(t[0], t[1], t[-1])  # Element
print(t[2:5], t[4:-1])    # Slicing
print(t[:2], t[3:])       # Slicing

AttributeError: 'numpy.ndarray' object has no attribute 'dim'

## 2D Array with Pytorch

In [19]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])

print(t)

AttributeError: module 'torch' has no attribute 'FloatTensor'

In [20]:
print(t.dim())        # rank
print(t.size())       # shape
print(t[:, 1])
print(t[:, 1].size())
print(t[:, :-1])

AttributeError: 'numpy.ndarray' object has no attribute 'dim'

## Shape, Rank, Axis

In [21]:
t = torch.FloatTensor([[[[1, 2, 3, 4],
                         [5, 6, 7, 8],
                         [9, 10, 11, 12]],
                       [[13, 14, 15, 16],
                        [17, 18, 19, 20],
                        [21, 22, 23, 24]]
                       ]])

AttributeError: module 'torch' has no attribute 'FloatTensor'

In [22]:
print(t.dim())  # rank  = 4
print(t.size()) # shape = (1, 2, 3, 4)

AttributeError: 'numpy.ndarray' object has no attribute 'dim'

## Mul vs Matmul

In [23]:
print('-------------')
print('Mul vs Matmul')
print('-------------')
m1 = torch.FloatTensor([[1,2], [3,4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape)    # 2 x 2
print('Shape of Matrix 2: ', m2.shape)    # 2 x 1
print(m1.matmul(m2)) # 2 x 1

m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape)    # 2 x 2
print('Shape of Matrix 2: ', m2.shape)    # 2 x 1
print(m1 * m2) # 2 x 2
print(m1.mul(m2))

-------------
Mul vs Matmul
-------------


AttributeError: module 'torch' has no attribute 'FloatTensor'

## Broadcasting

In [24]:
#Same Shape
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])
print(m1 + m2)

AttributeError: module 'torch' has no attribute 'FloatTensor'

In [25]:
#Vector + Scalar
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3]])   # [3] == [[3,3]]
print(m1 + m2)

AttributeError: module 'torch' has no attribute 'FloatTensor'

In [ ]:
#2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

## Mean

In [ ]:
t = torch.FloatTensor([1,2])
print(t.mean())

In [ ]:
# Can't use mean() on integers
t = torch.LongTensor([1, 2])
try:
    print(t.mean())
except Exception as exc:
    print(exc)

In [ ]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

In [ ]:
print(t.mean())
print(t.mean(dim=0))   #dim = dimension
print(t.mean(dim=1))
print(t.mean(dim=-1))

## Sum

In [ ]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

In [ ]:
print(t.sum())
print(t.sum(dim=0))   #dim = dimension
print(t.sum(dim=1))
print(t.sum(dim=-1))

## Max and Argmax

In [ ]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

In [ ]:
print(t.max())                      # Returns one value: max

In [ ]:
print(t.max(dim=0))                 # Returns two values: max and argmax (specified the dimension)
print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1])

In [ ]:
print(t.max(dim=1))
print(t.max(dim=-1))

## View

In [ ]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])

ft = torch.FloatTensor(t)
print(ft.shape)

In [ ]:
print(ft.view([-1, 3]))
print(ft.view([-1, 3]).shape)

In [ ]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

## Squeeze

In [ ]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

In [ ]:
print(ft.squeeze())
print(ft.squeeze().shape)

## Unsqueeze

In [ ]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

In [ ]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

In [ ]:
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

In [ ]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

In [ ]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

## Scatter ( ; one-hot encoding)

In [ ]:
lt = torch.LongTensor([[0], [1], [2], [0]])
print(lt)

In [ ]:
one_hot = torch.zeros(4, 3) # batch_size = 4, classes = 3
one_hot.scatter_(1, lt, 1)
print(one_hot)

## Casting

In [ ]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

In [ ]:
print(lt.float())

In [ ]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

In [ ]:
print(bt.long())
print(bt.float())

## Concatenation

In [ ]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [ ]:
print(torch.cat([x, y], dim=0))
print(torch.cat([x, y], dim=1))

## Stacking

In [ ]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [ ]:
print(torch.stack([x, y, z]))
print(torch.stack([x, y, z], dim=1))

In [ ]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

## Ones and Zeros Like

In [ ]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

In [ ]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

## In-Place Operation

In [ ]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [ ]:
print(x.mul(2.))
print(x)
print(x.mul_(2.))
print(x)

## Miscellaneous

### Zip

In [ ]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

In [ ]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)